# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBoxNumPreguntas = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNumPreguntas.setGeometry(QtCore.QRect(350, 590, 131, 81))
        self.spinBoxNumPreguntas.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxNumPreguntas.setMaximum(51)
        self.spinBoxNumPreguntas.setObjectName("spinBoxNumPreguntas")
        self.bConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.bConfirmar.setGeometry(QtCore.QRect(560, 580, 301, 91))
        self.bConfirmar.setObjectName("bConfirmar")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 1111, 561))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.eTitulo = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.eTitulo.setFont(font)
        self.eTitulo.setObjectName("eTitulo")
        self.eSubTitulo = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eSubTitulo.setFont(font)
        self.eSubTitulo.setObjectName("eSubTitulo")
        self.ePregunta = QtWidgets.QLabel(self.splitter)
        self.ePregunta.setObjectName("ePregunta")
        self.eRespuestas = QtWidgets.QLabel(self.splitter)
        self.eRespuestas.setObjectName("eRespuestas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trivia´s API quest"))
        self.bConfirmar.setText(_translate("MainWindow", "Aceptar"))
        self.eTitulo.setText(_translate("MainWindow", "Prueba"))
        self.eSubTitulo.setText(_translate("MainWindow", "Categoria"))
        self.ePregunta.setText(_translate("MainWindow", "Pregunta"))
        self.eRespuestas.setText(_translate("MainWindow", "Respuestas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
