# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBoxNumPreguntas = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNumPreguntas.setGeometry(QtCore.QRect(940, 220, 61, 41))
        self.spinBoxNumPreguntas.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxNumPreguntas.setMaximum(51)
        self.spinBoxNumPreguntas.setObjectName("spinBoxNumPreguntas")
        self.bConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.bConfirmar.setGeometry(QtCore.QRect(1010, 220, 101, 41))
        self.bConfirmar.setObjectName("bConfirmar")
        self.BotonConfRespuesta = QtWidgets.QPushButton(self.centralwidget)
        self.BotonConfRespuesta.setGeometry(QtCore.QRect(1010, 540, 101, 41))
        self.BotonConfRespuesta.setObjectName("BotonConfRespuesta")
        self.spinBoxNumRespuesta = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNumRespuesta.setGeometry(QtCore.QRect(940, 540, 61, 41))
        self.spinBoxNumRespuesta.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxNumRespuesta.setMinimum(1)
        self.spinBoxNumRespuesta.setMaximum(4)
        self.spinBoxNumRespuesta.setObjectName("spinBoxNumRespuesta")
        self.textAreaPregunta = QtWidgets.QTextBrowser(self.centralwidget)
        self.textAreaPregunta.setGeometry(QtCore.QRect(40, 290, 1071, 192))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textAreaPregunta.setFont(font)
        self.textAreaPregunta.setObjectName("textAreaPregunta")
        self.textAreaRespuestas = QtWidgets.QTextBrowser(self.centralwidget)
        self.textAreaRespuestas.setGeometry(QtCore.QRect(40, 490, 541, 192))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        self.textAreaRespuestas.setFont(font)
        self.textAreaRespuestas.setObjectName("textAreaRespuestas")
        self.texAreaResultados = QtWidgets.QTextBrowser(self.centralwidget)
        self.texAreaResultados.setGeometry(QtCore.QRect(825, 10, 291, 192))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.texAreaResultados.setFont(font)
        self.texAreaResultados.setObjectName("texAreaResultados")
        self.eTitulo = QtWidgets.QLabel(self.centralwidget)
        self.eTitulo.setGeometry(QtCore.QRect(40, 20, 781, 161))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.eTitulo.setFont(font)
        self.eTitulo.setObjectName("eTitulo")
        self.eSubTitulo = QtWidgets.QLabel(self.centralwidget)
        self.eSubTitulo.setGeometry(QtCore.QRect(40, 200, 881, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eSubTitulo.setFont(font)
        self.eSubTitulo.setObjectName("eSubTitulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trivia´s API quest"))
        self.bConfirmar.setText(_translate("MainWindow", "Aceptar"))
        self.BotonConfRespuesta.setText(_translate("MainWindow", "Enviar Respuesta"))
        self.eTitulo.setText(_translate("MainWindow", "Prueba"))
        self.eSubTitulo.setText(_translate("MainWindow", "Categoria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
